### ISSUE TITLE
git error when Build docker image

### ISSUE THREAD

**Issue by ahmedcdamrani** [GokuMohandas/follow#9]
Hi, 
I try to build the docker image from the latest. I can't build the image.
At the end I have this error message:
 ERROR: Error [Errno 2] No such file or directory: 'git': 'git' while executing command git version
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?

Ahmed

Obtaining file:///mlops
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting snorkel@ git+git://github.com/snorkel-team/snorkel.git@4d1555654496f0d9e089edc26a8aa102cdfbb5da
  Cloning git://github.com/snorkel-team/snorkel.git (to revision 4d1555654496f0d9e089edc26a8aa102cdfbb5da) to /tmp/pip-install-k8dhrh4r/snorkel_11e0370d46774cf2afd57f3f4a66bcd1
  ERROR: Error [Errno 2] No such file or directory: 'git': 'git' while executing command git version
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?
The command '/bin/sh -c apt-get update     && apt-get install -y --no-install-recommends gcc build-essential     && rm -rf /var/lib/apt/lists/*     && python -m pip install --upgrade pip setuptools wheel     && python -m pip install -e . --no-cache-dir     && apt-get purge -y --auto-remove gcc build-essential' returned a non-zero code: 1

**Comment by GokuMohandas** [comment]
Hmm I didn't run into this issue but could be some defaults in my image. You can add this command before the operations above to install git into your docker image.

```dockerfile
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y git
```

**Comment by ahmedcdamrani** [comment]
Thank you!
